runtime: python27
api_version: 1
threadsafe: true 

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /images
  static_dir: images


- url: /.*
  script: gallery.app

libraries:
- name: PIL
  version: "1.1.7"
- name: jinja2
  version: "2.6"